app:
  bot_link: "https://t.me/KingTimeDonateBot"
  public_url: ""

bot:
  token: ""   # берётся из ENV BOT_TOKEN

api:
  token: ""   # берётся из ENV API_TOKEN

payment:
  fio: "Маклаков Дмитрий Алексеевич"
  card: ""            # берётся из ENV CARD_NUMBER
  comment_prefix: "KT"
  code_length: 8

# ================== ТОВАРЫ ==================
products:

  # ---------- ДОНАТ РАНГИ ----------
  magister:
    title: "MAGISTER"
    price: 59
    type: "donate"
    announce: "донат MAGISTER"
    commands:
      - "lp user {nick} parent set magister"

  imperator:
    title: "IMPERATOR"
    price: 79
    type: "donate"
    announce: "донат IMPERATOR"
    commands:
      - "lp user {nick} parent set imperator"

  dragon:
    title: "DRAGON"
    price: 129
    type: "donate"
    announce: "донат DRAGON"
    commands:
      - "lp user {nick} parent set dragon"

  tiger:
    title: "TIGER"
    price: 239
    type: "donate"
    announce: "донат TIGER"
    commands:
      - "lp user {nick} parent set tiger"

  rabbit:
    title: "RABBIT"
    price: 469
    type: "donate"
    announce: "донат RABBIT"
    commands:
      - "lp user {nick} parent set rabbit"

  dhelper:
    title: "D.HELPER"
    price: 699
    type: "donate"
    announce: "донат D.HELPER"
    commands:
      - "lp user {nick} parent set dhelper"

  king:
    title: "KING"
    price: 999
    type: "donate"
    announce: "донат KING"
    commands:
      - "lp user {nick} parent set king"

  cobra:
    title: "COBRA"
    price: 1299
    type: "donate"
    announce: "донат COBRA"
    commands:
      - "lp user {nick} parent set cobra"

  admin:
    title: "D.ADMIN"
    price: 2999
    type: "donate"
    announce: "донат D.ADMIN"
    commands:
      - "lp user {nick} parent set admin"

  # ---------- КЕЙСЫ ----------
  rilik_1:
    title: "1 кейс с Риликами"
    price: 50
    type: "case"
    announce: "1 кейс с Риликами"
    commands:
      - "cases give {nick} rilik 1"

  rilik_3:
    title: "3 кейса с Риликами"
    price: 100
    type: "case"
    announce: "3 кейса с Риликами"
    commands:
      - "cases give {nick} rilik 3"

  rilik_5:
    title: "5 кейсов с Риликами"
    price: 200
    type: "case"
    announce: "5 кейсов с Риликами"
    commands:
      - "cases give {nick} rilik 5"

  sdonate_1:
    title: "1 супер донат кейс"
    price: 139
    type: "case"
    announce: "1 супер донат кейс"
    commands:
      - "cases give {nick} sdonate 1"

  sdonate_3:
    title: "3 супер донат кейса"
    price: 239
    type: "case"
    announce: "3 супер донат кейса"
    commands:
      - "cases give {nick} sdonate 3"

  sdonate_5:
    title: "5 супер донат кейсов"
    price: 359
    type: "case"
    announce: "5 супер донат кейсов"
    commands:
      - "cases give {nick} sdonate 5"

  # ---------- УСЛУГИ ----------
  unban:
    title: "Разбан"
    price: 250
    type: "service"
    announce: "разбан"
    commands:
      - "unban {nick}"

  unmute:
    title: "Размьют"
    price: 150
    type: "service"
    announce: "размьют"
    commands:
      - "unmute {nick}"

# ================== АДМИНЫ ==================
admins:
  - 1335389768
  - 1414803249
